### ISSUE TITLE
有些ID正常使用，有些会ID报错

### ISSUE THREAD

**Issue by akua0z** [BalconyJH/nonebot_plugin_r6s#10]
有些ID可以用，有些就会查询报错，这是啥原因呢
而且可以正常使用的ID也必须直接私聊机器人才能正常发图，在群聊中发送查询，机器人不发图响应，bot中也无报错信息
人有点麻。。。
![`J(UZFRZJUR98K` 22Q)`8H](https://user-images.githubusercontent.com/113225788/189481759-e4a1a25b-c970-4c4d-8403-68cc5860a666.png)
图为私聊机器人的情况下，bot的报错信息

**Comment by abrahum** [comment]
爬虫部分已长时间未维护，无法获取数据实属正常，暂无恢复维护计划（咕咕咕
