### ISSUE TITLE
插件报错，而且群里不生效

### ISSUE THREAD

**Issue by LSGLSH** [BalconyJH/nonebot_plugin_r6s#11]
![QQ图片20220927114831](https://user-images.githubusercontent.com/106002475/192427716-0ae7eacf-b8c1-4b8c-b897-937ff5d851ec.png)
![QQ图片20220927114911](https://user-images.githubusercontent.com/106002475/192427738-e56545f0-ac47-4437-a47d-700bb757fa6f.png)

可以的话，留个联系方式吧

**Comment by abrahum** [comment]
nonebot群里有我，本项目预计将由 @BalconyJH 接手

**Comment by LSGLSH** [comment]
> nonebot群里有我，本项目预计将由 @BalconyJH 接手

本人不在nb群，大佬，所以说来问问看我QQ2368343278

**Comment by BalconyJH** [comment]
在修了在修了😭
