### ISSUE TITLE
Pillow依赖版本过旧，与其他插件冲突

### ISSUE THREAD

**Issue by OnlyblackTea** [BalconyJH/nonebot_plugin_r6s#12]
**nonebot-plugin-r6s 0.4.2 requires Pillow<9.0.0,>=8.4.0, but you have pillow 9.3.0 which is incompatible.**

**nonebot-plugin-ncm 1.5.3 requires Pillow<10.0.0,>=9.3.0, but you have pillow 8.4.0 which is incompatible.**

如题，希望可以依赖更新版本的pillow

**Comment by BalconyJH** [comment]
收到
