### ISSUE TITLE
作者你好，请问该插件仅适用于私聊吗？

### ISSUE THREAD

**Issue by VoplsX** [BalconyJH/nonebot_plugin_r6s#3]
如题，私聊有效，但是群聊并无反应，能否考虑添加群聊有效呢，谢谢作者做的插件，辛苦了！

**Comment by abrahum** [comment]
虽然你 close 了，大概找到了问题了，你应该是没有 at 你的 bot 。

类似问题可以查看 -> [Nonebot2文档](https://v2.nonebot.dev/)
