### ISSUE TITLE
作者你好，能接收到信息但是不自动回复；私聊和群都没反应

### ISSUE THREAD

**Issue by LeonX86** [BalconyJH/nonebot_plugin_r6s#5]
02-17 23:52:10 [INFO] websockets | connection open
02-17 23:52:15 [SUCCESS] nonebot | ONEBOT V11 1851377216 | [message.private.friend]: Message -1910991340 from 1843164971 "r6s Diremind"
02-17 23:52:15 [DEBUG] nonebot | Checking for matchers in priority 1...
02-17 23:52:15 [DEBUG] nonebot | Checking for matchers in priority 5...
02-17 23:52:25 [SUCCESS] nonebot | ONEBOT V11 1851377216 | [message.private.friend]: Message 1612117816 from 1843164971 "r6sDiremind"
02-17 23:52:25 [DEBUG] nonebot | Checking for matchers in priority 1...
02-17 23:52:25 [DEBUG] nonebot | Checking for matchers in priority 5...

**Comment by BalconyJH** [comment]
请提供nonebot启动阶段log

**Comment by LeonX86** [comment]
> 请提供nonebot启动阶段log
[root@VM-0-14-centos bot_linux]# python3 bot.py 
02-17 23:52:08 [SUCCESS] nonebot | NoneBot is initializing...
02-17 23:52:08 [INFO] nonebot | Current Env: dev
02-17 23:52:08 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 53245, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': {'1843164971', '1851377216'}, 'nickname': {'bot', 'awesome'}, 'command_start': {'/', '!'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'ncm_song': 'True', 'leetcode_qq_groups': [690742238], 'ncm_admin': ['owner', 'admin'], 'environment': 'dev', 'leetcode_inform_time': '[{"HOUR":19,"MINUTE":38},]', 'qweather_apitype': 1, 'leetcode_qq_friends': [1843164971], 'qweather_apikey': '73417184b8374a4d93af407f1c326f7d', 'ncm_phone': 13961637346, 'white_list': [], 'ncm_list': 'True', 'ncm_priority': 2, 'ncm_password': 'woshihaoren@115'}
02-17 23:52:08 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
02-17 23:52:08 [SUCCESS] nonebot | Succeeded to import "nonebot.plugins.echo"
02-17 23:52:08 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_r6s"
02-17 23:52:08 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
02-17 23:52:08 [SUCCESS] nonebot | Running NoneBot...
02-17 23:52:08 [DEBUG] nonebot | Loaded adapters: OneBot V11
02-17 23:52:08 [INFO] uvicorn | Started server process [16345]
02-17 23:52:08 [INFO] uvicorn | Waiting for application startup.
02-17 23:52:08 [INFO] uvicorn | Application startup complete.
02-17 23:52:08 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:53245 (Press CTRL+C to quit)
02-17 23:52:10 [INFO] uvicorn | ('127.0.0.1', 53254) - "WebSocket /onebot/v11/ws/" [accepted]
02-17 23:52:10 [INFO] nonebot | OneBot V11 | Bot 1851377216 connected
02-17 23:52:10 [INFO] websockets | connection open
02-17 23:52:15 [SUCCESS] nonebot | ONEBOT V11 1851377216 | [message.private.friend]: Message -1910991340 from 1843164971 "r6s Diremind"
02-17 23:52:15 [DEBUG] nonebot | Checking for matchers in priority 1...
02-17 23:52:15 [DEBUG] nonebot | Checking for matchers in priority 5...
02-17 23:52:25 [SUCCESS] nonebot | ONEBOT V11 1851377216 | [message.private.friend]: Message 1612117816 from 1843164971 "r6sDiremind"
02-17 23:52:25 [DEBUG] nonebot | Checking for matchers in priority 1...
02-17 23:52:25 [DEBUG] nonebot | Checking for matchers in priority 5...
^C02-17 23:52:55 [INFO] uvicorn | Shutting down
02-17 23:52:55 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 1851377216 closed by peer
02-17 23:52:55 [INFO] websockets | connection closed
02-17 23:52:55 [INFO] uvicorn | Waiting for application shutdown.
02-17 23:52:55 [INFO] uvicorn | Application shutdown complete.
02-17 23:52:55 [INFO] uvicorn | Finished server process [16345]

**Comment by abrahum** [comment]
` 'command_start': {'/', '!'}`

你需要按照设置在你的指令前添加起始符。

更多配置详情请参考 Nonebot2 官方文档（或添加 Nonebot 群提问）。

**Comment by LeonX86** [comment]
非常感谢
