### ISSUE TITLE
干员基础信息查询出错

### ISSUE THREAD

**Issue by octopusYan** [BalconyJH/nonebot_plugin_r6s#7]
player.py:230 行
 data["SeasonRanks"] 为空时返回查询出错

**Comment by BalconyJH** [comment]
请提供详细描述

**Comment by octopusYan** [comment]
> 请提供详细描述

0.4.2版本，插件加载、启动时无报错
r6s Accustomone, 会返回 查询出错
如果需要其他信息请说明

**Comment by octopusYan** [comment]
还需要什么其他描述么？

**Comment by Kabuda-czh** [comment]
> player.py:230 行 data["SeasonRanks"] 为空时返回查询出错

在 `__init__.py` 第 48 行中已经进行了异常捕获了, 但为什么还会报错?
```python
try:
    player = new_player_from_r6scn(data)
except:
    await matcher.finish("查询干员出错『%s』" % username)
    return
```

你描述的返回出错是指的机器人的回复还是控制台的打印异常?
如果机器人返回的查询出错, 即指数据在**中文站**中并无返回 所以为异常

**Comment by octopusYan** [comment]
> > player.py:230 行 data["SeasonRanks"] 为空时返回查询出错
> 
> 在 `__init__.py` 第 48 行中已经进行了异常捕获了, 但为什么还会报错?
> 
> ```python
> try:
>     player = new_player_from_r6scn(data)
> except:
>     await matcher.finish("查询干员出错『%s』" % username)
>     return
> ```
> 
> 你描述的返回出错是指的机器人的回复还是控制台的打印异常? 如果机器人返回的查询出错, 即指数据在**中文站**中并无返回 所以为异常

我指的是机器人回复**查询出错**。

因为我查看了信息查询接口正常返回有其他数据，那个数组空了机器人就直接回复**查询出错**，而不是跳过空数组返回其他正常数据
![image](https://user-images.githubusercontent.com/70868034/170528331-97819270-0605-4363-b010-98768aaf49bc.png)

**Comment by octopusYan** [comment]
还是 **r6s Accustomone** 命令
image.py:88行 在 StatCR 为空的情况下也会报错
![image](https://user-images.githubusercontent.com/70868034/170536134-ba576ee4-62e2-4416-944c-2b6273a4d7b7.png)

**Comment by Kabuda-czh** [comment]
大概情况了解了, 我回去把逻辑更改一下

**Comment by octopusYan** [comment]
> 大概情况了解了, 我回去把逻辑更改一下

大大辛苦了

**Comment by Kabuda-czh** [comment]
> > 大概情况了解了, 我回去把逻辑更改一下
> 
> 大大辛苦了

大概改好了, 但是还没测试, 我估计你这样没有数据的账号展现出来的效果不会太理想, 因为数据取自中文站, 中文站查不到就是没什么数据的哦
晚上测了之后会pr一下

**Comment by abrahum** [comment]
现在数据都是滞后的，没啥更新的动力😂

**Comment by Kabuda-czh** [comment]
> 现在数据都是滞后的，没啥更新的动力😂

要不走tracker?
