### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by Xiao-yux** [BalconyJH/nonebot_plugin_r6s#8]
![EDHMAKJRFP{ CU1}`B6G%7D](https://user-images.githubusercontent.com/79674967/184783806-305300c6-35b8-483f-ab69-d88da68cb235.jpg)
![image](https://user-images.githubusercontent.com/79674967/184783838-445c6841-96f5-4be4-8c79-3957e0e69626.png)
名字没错啊

**Comment by abrahum** [comment]
本插件已较长时间未维护，可能爬取的网站接口发生了变化，有空的话再修复（咕咕咕

**Comment by Xiao-yux** [comment]
（咕咕咕

**Comment by Xiao-yux** [comment]
咕咕咕
