### ISSUE TITLE
返回数据具有随机性

### ISSUE THREAD

**Issue by thankU-ubi** [BalconyJH/nonebot_plugin_r6s#9]
搜索ID cat.sann,第一次给到的数据只到Y4S1，过了一会搜变成了Y7S1
![QQ图片20220825225146](https://user-images.githubusercontent.com/104612463/186698037-f2692b6a-e44d-43bc-94be-fec5d599e1f3.png)
![QQ图片20220825225155](https://user-images.githubusercontent.com/104612463/186698057-43ae0c01-3006-49f8-9fe6-609c55108dad.png)
搜我自己的ID只有报错
![QQ图片20220825225408](https://user-images.githubusercontent.com/104612463/186698667-a5835db6-e500-4a40-998b-186bcbc0ea54.png)
BOT和cqhttp都是正常无报错的

**Comment by BalconyJH** [comment]
1 数据刷新有延迟好像是r6scn的机制
2 已收到类似出错反馈，已进入待修复队列
